[package]

# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Extension Template"
author = "Amr Mousa"
maintainer = "Amr Mousa"
description="TAR extension for Isaac Lab"
repository = "https://github.com/ammousa/TARLoco"
keywords = ["extension", "template", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}

# NOTE: Add additional dependencies here

[[python.module]]
name = "tarloco"

[isaaclab_settings]
# Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
